#!/usr/bin/env python
# -*- coding: utf-8 -*-  

import os

class CfgInfo :
	mosesdecoder_path = "/opt/translation/moses/"
	irstlm_path = "/opt/translation/irstlm/"
	giza_path = "/opt/translation/mgizapp/"

	training_corpus_path = "/home/xwshi/data/Corpus-Bleu/0/"
	# training_corpus_path = "/home/xwshi/data/WMT/original/"
	# test_corpus_path = "/home/xwshi/data/WMT/original/"
	# training_corpus_path = "/home/share/data/BOLT_Phase/Tokenized/Train/"
	# test_corpus_path = "/home/share/data/BOLT_Phase/Tokenized/Train/"
	# test_corpus_path = "/home/share/data/BOLT_Phase/Tokenized/Test/"
	# training_corpus_path = "/home/xwshi/data/double/"
	# test_corpus_path = "/home/xwshi/data/double/"
	# training_corpus_path = "/home/xwshi/data/CHT/original/"
	# test_corpus_path = "/home/xwshi/data/CHT/original/"
	# training_corpus_path = "/home/xwshi/data/wmt/europarl/"
	# test_corpus_path = "/home/xwshi/data/wmt/europarl/"
	# training_corpus_path = "/home/xwshi/data/CHT/notok/"
	# test_corpus_path = "/home/xwshi/data/CHT/notok/"
	# training_corpus_path = "/home/xwshi/data/CHT/cht-giga2/"
	# test_corpus_path = "/home/xwshi/data/BLOT/noseg/"
	# test_corpus_path = "/home/xwshi/data/CHT/cht-giga/"
	# training_corpus_path = "/home/xwshi/data/gale-p1/tok/"
	# test_corpus_path = "/home/xwshi/data/gale-p1/tok/"

	# nplm_path = "/opt/translation/nplm/"
	filename = "C_B.Train"
	devfilename = "C_B.Dev"
	# filename = "WMT.Train"
	# devfilename = "WMT.Dev"
	# testfilename = "WMT.Test"
	# filename = "gale.comb"
	# testfilename = "gale.comb"
	# devfilename = "CHT.Dev"
	# filename = "CHT.Train"
	# testfilename = "CHT.Test"
	# testfilename = "SMS.Test"
	# testfilename = "CHT.Dev"
	# filename = "europarl-v7.fr-en"
	# target_id = "fr"
	# source_id = "en"
	source_id = "zh"
	target_id = "en"
	workspace = "/home/xwshi/easymoses_workspace/"
	threads = "32"
	sentence_length = "80"